FROM nginx:latest

# Change Nginx config to listen on port 8080
RUN sed -i 's/listen\(.*\)80;/listen 8080;/' /etc/nginx/conf.d/default.conf

RUN chmod -R g+rwx /var/cache/nginx /etc/nginx /var/run /var/log/nginx

USER 101
