apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: quay.io/igou/nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
